# Nombre de la app
spring.application.name=notes-app

# Configuración de la base de datos (H2 guardará un archivo en la carpeta 'data')
spring.datasource.url=jdbc:h2:file:./data/notesdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Hibernate: Esto crea las tablas automáticamente basándose en tus clases de Java
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Consola para ver la base de datos desde el navegador
spring.h2.console.enabled=true